spring:
  kafka:
    producer:
      bootstrap-servers: 172.18.0.101:9092
    consumer:
      bootstrap-servers: 172.18.0.101:9092
      group-ids:
        order-catalog: catalogGroup
    topics:
      order-to-catalog: book-catalog-topic