spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(uEbqEYsvcO6g+Nv/pR91tggoYY5R0swYVHbMYWxUxUiUBmHRB/t3YtYdhye7G6a4jdu+zXnXSYCITNauVI7Dq7SRGuR2SXpaZTpJ2QzLaaX9i8fjyeQvYsMwuZZpbPREOJUC4ruNVPMcBTQBwZ7nNZMw5/ABdkzm2Z3Y4QThTeE=)
    username: ENC(BHmzH6N1SF+8i28j1sGPGr/5CLXsirLLLobj6Y0EeabsvuBZ9PUntRr4A/MNwHce)
    password: ENC(amiQL2z0fbPr5ivcMingFGTFPPbEcvVWbwR4yA5ZV8/mCxWB/uZW/yrB21NSmOxY)

jasypt:
  encryptor:
    password: '{cipher}AQB4liDwprFZBvNEjaIwpItkgR2WZt1KhJhx8ZVanP9KuPsCmsq/p8BdmU/3+i1x15jgW3FjIyxV5JAOyTGfecru96eZ11ZY6a3q+anhAHQ3pXtpAXtTK6NMQc4yWiqPmAP1pyZJlSPagiDxgy85n3ncthgdAIEZwa24woKWb3paBGF03TpZ2Yjdt5MSugX6Udph4gNW2zQNBrrBoLgzqe/crxCnKpVmmCHgPTGuA0TlcVtFsICWCLX4t4oMvaNfEbfKg6RiOTxcyJrQ+UN5jlAN6i+KZz7H2kj8HTtP0ykx4rwXXBPqcrSIh29LqDmwTrjKF8/egPCTjcCgsoWl21cYTi6EZeFGzNWaiI8a7VHFXkd8dsZwPv1vCmURn6bbz7g='